return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "2020.04.10",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 390,
  height = 25,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 12,
  nextobjectid = 210,
  properties = {
    ["darkness"] = 0.10000000000000001
  },
  tilesets = {
    {
      name = "MyTileset",
      firstgid = 1,
      filename = "MyTileset.tsx",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      terrains = {},
      tilecount = 13,
      tiles = {
        {
          id = 1,
          image = "wall old.png",
          width = 32,
          height = 32
        },
        {
          id = 3,
          image = "prototype_wall.png",
          width = 32,
          height = 32
        },
        {
          id = 4,
          image = "wall black.png",
          width = 32,
          height = 32
        },
        {
          id = 9,
          image = "blueDark1.png",
          width = 32,
          height = 32,
          probability = 0.2
        },
        {
          id = 10,
          image = "blueDark2.png",
          width = 32,
          height = 32
        },
        {
          id = 11,
          image = "blueDark3.png",
          width = 32,
          height = 32
        },
        {
          id = 12,
          image = "Hot_tile.png",
          width = 32,
          height = 32
        },
        {
          id = 13,
          image = "grass1.png",
          width = 32,
          height = 32
        },
        {
          id = 14,
          image = "dirt.png",
          width = 32,
          height = 32
        },
        {
          id = 15,
          image = "sky1.png",
          width = 32,
          height = 32
        },
        {
          id = 16,
          image = "sky3.png",
          width = 32,
          height = 32
        },
        {
          id = 17,
          image = "sky2.png",
          width = 32,
          height = 32
        },
        {
          id = 18,
          image = "sky4.png",
          width = 32,
          height = 32
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 390,
      height = 25,
      id = 2,
      name = "Background",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zstd",
      data = "KLUv/WBYl+1GAJbbG5IQAAAAAGVAACAQGAAYABgAbxb8f5MN/m1Z8O+XcvD/+8wF7z9JAgBQz8Lf18N/min8TymTYZ9MCvf/SsJ/qsMP1yRZ/HklJfbllxxdn6dyjk/Pov+uC/8F8f9Lxv+V43+Jf0ni847vly3JYm9JXoXTqGPrL/MWQALZiNtcDhNASyBBJVDhEogRCZSABDGWIIQJQpKgJ7ACCSWjOJz1/yt2PBuvWwZhK2X8Dsus1vdC/4JD1umq4Se+T9FNESf7+lOd6DSgeiK+oB1c6Qqr8d+w8MQ5DrLw6QzHNV6AjHbe28vvIbnqzha4zbYKjDse5JxEXmKz4YueVTq4F/E/CnDAjYumjAYgwL+O1Cs4NlLh2+hdT6OU//NV9yG0eD+a2fVeHfemG5axkl/Ng35DFDvJl0h3O46BYTZXLvMp5RYks1d3a+mex/J2iYXF5oy+ev7u/TCq95POnxnLG/mUmfaGic+IdivlbH8tZQWDn+e2M8C47Ze9mc+ha7TbPRrSclF1PCz7h1+nSxsxULt3Rte+g7EnVdP7NJ1g6Dm4+7af8+4nhwN2a3TsLKnhZ1uCkjZKMIr1eRO5A3dsHvBqg0910Lkj2D8YHiYXrm/e5UZ2F+38jUtGdjc8Q9sR6u7ET0X0YBg+BzqhXTEZYc/K/WLgH5OWM8gm3sesL7rUHE3i5tfUshvha9EZxOXkOb//4HmQOSo93SNaPTA0QLwnhtgqviW9OoBw/N9YGXFr65OFG8/bRxwLvrDfiJ57/9ir/3D0vxNU7x8XfhSc82CC3upgo8x9VOHyxX4KCyK8n2cSDM1QgHdCOlgjYxjoNosD+hXvRbeoZ00c6I/ntWJiiic272GOJ5fnr/ngwEW2E+6FGd7OvndvECznzK2/GW+fvNJnZqllf5qQ488F+CEa5+s39smfyU/mUvzZGfLm32Rfvv2myUHwDJmjWcx7nVQ4+21fm6f/QJp9cI0x090mXTTPMlw90+2JjSD5Mvd/7h73vkPZzdtHLnNu5Gu24idTyNl0ubpZbv+CFqdOIWt5vP2x65le9BDQ56oXVY0P6tXJQQWYYkBqXmeQMBNlWemB9ynTOkSHhGTu+tu6p78Pj5sH5Pl+BN336dlm1rdjKs7rfe1InumrJTZn3uRcp4jXnMfmavNiLGJsmvNfHwi/3KTx/T349nDncdRp1x6i2LI5+e8ueycsjQfEMpPX+26FE3iU9QTmnLzKRhee9yLmo97OH1vMed1zlRt+O97DpvgPPX+FzPt+X+IHoqdm2p95ZKS00ryJzF950HVZkHDbPjzV28wGX5JP7c9x8k/OxqeHTvr5Lr4MvEXMsa3c/z07drQTZ8Y+if1M8eoTDp3axoUvcN5vco/jN/KAP86Ed7+ZQyaR8e5ybEBYq4ZHNxiWct02u/f3QKftA3iF85lhasWu+sPvJdUvBveDwi+a1w6KPD4XXRzzaSn3Bo4SmOZhy5srY/HlUSFHgw0+7Hux+2FifHL2vJxL+ZUzaeduq34cvWpP8c5Xa+TE9hEEA7EO8qnmO8cRR6HpkZe3yMPjSLEqOLwL3U4/+1Yrw8lcQd7r6rfablNfYb3pMjnveTXMCJnmp1F1lzJz+pXFGXYwu1f7vU/R3hvc97bLOZg9TSQkcoA9eJyYXYCYWbbm00Nnlo/+CZ6Vp2JleFqDyj0ni4q9BlPB2be2h0vxZy7UFwZ9xnM9NdkRFnO8mozGUCw6oz3r/xbiV4iRoV27ra3m7/j8/aCTuBor8rPVFLtjaGQGfD/L7WunsdGqbie+0F7foaI9bu5NheNOWLfc/nq/h+PaOg32rVNhsRZhrX/QxfxwlPf9w+0ePzIAqD/ybmx2k7+coLqFtvf/zj1+9RdjTcW4h3e5zCzQLWNmnOTnAgY8cn7jr4mG3kYx+uaCEPxrJfqUexU6aH2Qlb3MJpBlu9o4ieBT6ANDEwicHPqFn8rTWewdUPq5CvCu2Kz2Xm/wbWxToyf3EoppPdEvh/azv+BcjxBngLo6G/xAMIXrh66n/OdcML9h824XP+fLj/Q+UF2JK5zKWfhXftZDe8a3tx2qz29517MdJvvI3oAfzJv6RT+nUY3Wo4F6Eptiwbm/+8zZiQ0vWF45s94/VobgUeA2bF6jfAk5VhxgSY/xmBMaOYE6CHPLmp3hi0Olb/OIefx5a2UvEsU6Aa/xxfAA3Sz6ijRIHjy3WPu94it7QvbqhLHH8Ux1nOsC3fe2j+33C3mEgXsa5ZdlI8ytWHVM/MxF3roZn34XiNg9/yXkznfFPD1fkqLXnt1mFr20q5r4an+YdFelXxEwMfn6sCPWsn1mrV7O1aPRjSDiIfQ4+03LHgKqm9fUMEDHlgglUrc9IPeT7An+/WIeaD22BY6x3LeHvdhqm2Cz3uAZ/yXojguFh/AEPB7tyvpCA/Z+AY9hazN5HgzwDiGAR1ETnLV1HgLmZfPzuLuH8CY8jtr0V/7mvk3XAv/e9rZkjE9ORPAutucH4P6uMpXXX1KkeMf0n33oArdndfb8ZMPqqfyUp32+l2uYTxnZY9NskwX+KI1uLXsU7jnX899DB4MlfhD4XHgEGfSYhXKS+my9Z7dRb4f2aUPaDX/QZn1uLwbHcuobJ/LPn9aqld45HGIYT2NwHikNHf2myMfivPXbTHwyBZOW17q9Air4SM7SPt4MjeeiglHV6CYPA9d3WQaeYtxykFUdxeJNjTm3UrVoebHX9jwD4buQkzIbRu9Ox537X3qU8g1KGJdzWgZZD6WO+LP7Rj81zmI3ZMuFE+W33uW8e4bG13HiEvwgQWbSO+u26dMuuP2Ukf3Dsb5HdaLjoDJjTeqixntsrTJcmvDE+yP7q+S1dG7on4Udd12WZE8jNa5t9bnXoNVf9+RKPdxbZo1WtsgvmwHnuaMSwmiwTWjvf8fsdDmgDq6voTOR+0RXzR8c0IO2ATynrEv6mRMvpjnwAjecs2W1NzIjmhsM6F/or/rvZVY/UBzoe9XQ2g7rGJhj1ZMTH3VIr15++R8="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 390,
      height = 25,
      id = 1,
      name = "Front",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zstd",
      data = "KLUv/WBYlx0LADKEBwrgQQD//7V+1hB9UFVVYVUp/DBIMhn8222gPSyRZICrqFC9ABCDTADEARKgEFgIGhRBwxAEDEHDEDQAQQMQVAQMAQPyAE6gVEgfHAnAiwIhCkYgLDABgQIBWA4A4K0KMqZgBMIGJo5LgAEerkEeusLdMgCWK3S4jkKLWGEddaZhATj9JT9g6YSS+bD6VPeNQf81RFxiTCGPpHKBgMHCCAzooPsHS2K8MKDvPs3vAFxVmHiMO20RwDJSDIYAcEMONvToO1223y2bFgCHRXjDVy4M38sqwUO+CrejEXrBfgiFc1zai21DxjVci8WhzRnsEIWGOmJsAdxXVdW6YrhPUOQCKyTZJSYEpQo5zNekQk2J1siGkqF370BE5h3Ek/OMgEKaYgKNb05Q0HMJ9d0hjMzYSpjtD1merJSyoazrEGbG5q7Vw5v8OvKEZ3pEW6Py34whBL9aDCfDdSCxGpEd8Qc="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 11,
      name = "Text",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 192,
          name = "",
          type = "",
          shape = "text",
          x = 11776,
          y = 352,
          width = 480,
          height = 64,
          rotation = 0,
          visible = true,
          text = "Thanks for playing",
          fontfamily = "MS Shell Dlg 2",
          pixelsize = 48,
          wrap = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "Collectables",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "FragilePlatforms",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "Walls",
      visible = false,
      opacity = 0.75,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 114,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 192,
          width = 1856,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 640,
          width = 1056,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 640,
          width = 384,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4224,
          y = 640,
          width = 608,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3232,
          y = 640,
          width = 576,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2272,
          y = 640,
          width = 544,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 124,
          name = "",
          type = "",
          shape = "rectangle",
          x = -32,
          y = 416,
          width = 32,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1856,
          y = 192,
          width = 5600,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 146,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7456,
          y = 192,
          width = 512,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7072,
          y = 608,
          width = 4128,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8384,
          y = 448,
          width = 2816,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 151,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8704,
          y = 224,
          width = 608,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 152,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9312,
          y = 256,
          width = 96,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9408,
          y = 288,
          width = 96,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9504,
          y = 320,
          width = 96,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9600,
          y = 352,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 156,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9664,
          y = 384,
          width = 96,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9760,
          y = 416,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9760,
          y = 0,
          width = 96,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 165,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9664,
          y = 0,
          width = 96,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9568,
          y = 0,
          width = 96,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9504,
          y = 0,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9408,
          y = 0,
          width = 96,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9856,
          y = 0,
          width = 960,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7968,
          y = 0,
          width = 1440,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 174,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 7968,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10816,
          y = 0,
          width = 64,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 180,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10880,
          y = 0,
          width = 64,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10944,
          y = 0,
          width = 64,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 182,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11008,
          y = 0,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11072,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11136,
          y = 0,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11136,
          y = 224,
          width = 64,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 186,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11072,
          y = 256,
          width = 64,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 187,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11008,
          y = 288,
          width = 64,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10944,
          y = 320,
          width = 64,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10880,
          y = 352,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 190,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10816,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 191,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10752,
          y = 416,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 193,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11200,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 194,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11200,
          y = 704,
          width = 1280,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 195,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11296,
          y = 608,
          width = 192,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 196,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11488,
          y = 640,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 197,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11520,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 198,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11328,
          y = 544,
          width = 96,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 199,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11648,
          y = 672,
          width = 608,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 200,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11680,
          y = 640,
          width = 320,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 201,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11744,
          y = 608,
          width = 256,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 202,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11776,
          y = 576,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 203,
          name = "",
          type = "",
          shape = "rectangle",
          x = 12320,
          y = 576,
          width = 160,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 204,
          name = "",
          type = "",
          shape = "rectangle",
          x = 12352,
          y = 448,
          width = 128,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 205,
          name = "",
          type = "",
          shape = "rectangle",
          x = 12448,
          y = 0,
          width = 32,
          height = 448,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 207,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11776,
          y = 352,
          width = 416,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "EventTriggers",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 208,
          name = "trigger_end_game",
          type = "",
          shape = "rectangle",
          x = 11200,
          y = 0,
          width = 1280,
          height = 800,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "Hazards",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 736,
          width = 416,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1856,
          y = 736,
          width = 416,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2816,
          y = 736,
          width = 416,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3808,
          y = 736,
          width = 416,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4832,
          y = 768,
          width = 2240,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7456,
          y = 480,
          width = 512,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "AutoMovingPlatforms",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5248,
          y = 352,
          width = 224,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 5248,
            ["ey"] = 480,
            ["isDeadly"] = false,
            ["speed"] = 150,
            ["sx"] = 5248,
            ["sy"] = 352
          }
        },
        {
          id = 126,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5248,
          y = 704,
          width = 224,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 5248,
            ["ey"] = 704,
            ["isDeadly"] = false,
            ["speed"] = 150,
            ["sx"] = 5248,
            ["sy"] = 576
          }
        },
        {
          id = 129,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5888,
          y = 480,
          width = 224,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 5888,
            ["ey"] = 480,
            ["isDeadly"] = false,
            ["speed"] = 150,
            ["sx"] = 5888,
            ["sy"] = 352
          }
        },
        {
          id = 130,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5888,
          y = 576,
          width = 224,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 5888,
            ["ey"] = 704,
            ["isDeadly"] = false,
            ["speed"] = 150,
            ["sx"] = 5888,
            ["sy"] = 576
          }
        },
        {
          id = 131,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6400,
          y = 352,
          width = 224,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 6400,
            ["ey"] = 480,
            ["isDeadly"] = false,
            ["speed"] = 150,
            ["sx"] = 6400,
            ["sy"] = 352
          }
        },
        {
          id = 132,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6400,
          y = 704,
          width = 224,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 6400,
            ["ey"] = 704,
            ["isDeadly"] = false,
            ["speed"] = 150,
            ["sx"] = 6400,
            ["sy"] = 576
          }
        },
        {
          id = 137,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5632,
          y = 352,
          width = 96,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 5632,
            ["ey"] = 736,
            ["isDeadly"] = true,
            ["speed"] = 300,
            ["sx"] = 5632,
            ["sy"] = 352
          }
        },
        {
          id = 138,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6208,
          y = 736,
          width = 96,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 6208,
            ["ey"] = 736,
            ["isDeadly"] = true,
            ["speed"] = 300,
            ["sx"] = 6208,
            ["sy"] = 352
          }
        },
        {
          id = 178,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7936,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 7936,
            ["ey"] = 512,
            ["isDeadly"] = true,
            ["speed"] = 300,
            ["sx"] = 7456,
            ["sy"] = 512
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "Trampolines",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 140,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7488,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 141,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7520,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 142,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7680,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 143,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7712,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 144,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7904,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 145,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7936,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 149,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8224,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "PlayerObjects",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 112,
          name = "player_spawn",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "player_checkpoint",
          type = "",
          shape = "rectangle",
          x = 4544,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "player_checkpoint",
          type = "",
          shape = "rectangle",
          x = 7232,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "player_checkpoint",
          type = "",
          shape = "rectangle",
          x = 8096,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
