return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "2020.04.10",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 268,
  height = 51,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 11,
  nextobjectid = 377,
  properties = {
    ["darkness"] = 0.10000000000000001
  },
  tilesets = {
    {
      name = "MyTileset",
      firstgid = 1,
      filename = "MyTileset.tsx",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      terrains = {},
      tilecount = 7,
      tiles = {
        {
          id = 1,
          image = "wall old.png",
          width = 32,
          height = 32
        },
        {
          id = 3,
          image = "prototype_wall.png",
          width = 32,
          height = 32
        },
        {
          id = 4,
          image = "wall black.png",
          width = 32,
          height = 32
        },
        {
          id = 9,
          image = "blueDark1.png",
          width = 32,
          height = 32,
          probability = 0.2
        },
        {
          id = 10,
          image = "blueDark2.png",
          width = 32,
          height = 32
        },
        {
          id = 11,
          image = "blueDark3.png",
          width = 32,
          height = 32
        },
        {
          id = 12,
          image = "Hot_tile.png",
          width = 32,
          height = 32
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 268,
      height = 51,
      id = 4,
      name = "Background",
      visible = true,
      opacity = 0.8,
      offsetx = 18,
      offsety = 9,
      properties = {},
      encoding = "base64",
      compression = "zstd",
      data = "KLUv/WCQ1DVEAGafJgnwEQB4wWrPST8lACMAIQDuKTtn5ef9MNP8dOEn36Pp9mScydOZyZNa8m3/vMfRBguAAYAB2WnPaZ/Jc5lptzJ/Pt+GG5Knb5s2ezu9ZwVWuMWa3e9Zswfmral5b3dmZ7qdbdlZWXput7dfu+2+5/rbDp6mVWG3OQP7dv5r9mYvxNnpOL900zbNWde5p21+7qedX8V5765t9gaE46jTyV8A8xdAVSQIJi1cARPAg0CAWAgAiQkAoHAAAIwFAHBgAAIUFIBAJAFAIiCDsjgNrFMDGXvv1/tJI1nR2lSPNOpYstMpospPPPn8Zjdf2P4DA2sVX5rvfcG2S2xx1Qn6WgeyJFrs+jx43ByrrasamDtUzGuG3L2IAxoOMiPqEb0f2VIZj4UDaYfAiZR7gyfKmDIb9Eq6vXfbC79XMcnPcCbmRjk/6iasQ/2J2HF+3ufP/TN2Mp6k3hLxkbZ09fMAWT2epwyNoVsw6P/lJigVjVd0dBCcU72+ihvEFzg4TFsz6BM/sQlmaQfHaxdyha8FLGu/P/87MQQa5p3BMaNSk4Efjl1CQjeMWv7HF/LcGFZHC5yCc/Gp4+bHXcKxus55u3G1fjOUP5Odqciivt7icoKMHFQ8EmTjT6Q47VfHRGVlKCdu/wA34zN0VpGnc5oB6ZvphJhgSxZzSHj9PEcmYBrrwT3wmz99NrwlIbFZrnhWpFiorJBzoe7/AptB2Q/YRalX5keBPo+L+etm1vghQBz3uwqj6TgNKRIBLlnhIb/a1X1uLcI/zKMZOSwragorDGk8HZWy7tFyV8gX8wAynzkwA90xoDkZTfgU4ea6b8Kvoi56e4BGEvn4fj7gi201tN/BhBEwbrWe4vb4ufU3e84fh+sPd6DppN0xn9xmuFrIxO6DokDf/gTZzTA11yo2FWklfyKavLkrYuzoGRyFUCplXD3OdLkrcj+woTB773CidxRyk3hUk+LMcO/oZNLKTzZd0We9V+ZnW9UUOzO9lBUZRJZrjkiIQOFYg3Ebo8oCrTgM/xyTvHTsY/KST+SUXktlA+hMJU7E5/itFbY+63/CUJ5yWB+GOuW99Xhx7d08Cp9PAGe4QeNBXCRGQYwMWJzhWQEBs5f5WDyxdy5cmDiarvon5GC5O5cJXZ2AIbll/d1EmD50XNVxIjfBNWX2jYCa4fPoz4brxCh5EnOWINzmu19a4C6p3QkiKl9UKNlT5X+L/IvuDKF9Zw4j6GahFsxwAY1O12JG7dwYf+kwGMJnuW/mRhZ/FhqB09hNmMXU3QDpd2Apg7doU9SdjpNwmp+B6sghZrDSQyTJnH9OjbwGb8vv5a7Cb8Si+eSb9ojXJO+e1YvoFpR7XDErN0PhIR04CT/8i9FwBZSA5LZ1q5hknaby3XvF5tBMmSMwg3OZw9tHwmzswi76CRTD/dmt8Pjapv7wdpBQhqTEboMB0RHbv3oz6DviKo5LgdfsrL6rZ9uIt6wyjv9AWpfqHE1mcATr6Yd5jm/qOBpJtWoGyqesHmn7suLsGIYS1xM1PPutKagAjm3JvxzLezPEeRk8/VyfLbwvxD9I0/6oFbvbUpeVoFxRLBEJjs/opZj+Myu/vC+saoXg4TV1mf+uiKtbYK7/+uyZN9OdABpr1S4sAjPQ7e/I16whDQHfmmLc/WVP3zzLze9+ejyNhgNnh/kqpxSf3TB00tJbDDt0neyObXHBcegSjq38y/fmSYyKzRBFA82DBDNgy5WOsZxuWRdMNqlnW6n1Wju3osf+CzOgcQZ7k1YupHIn94+MjdkAxFqOHU6j9iRlVrhwnwl7OKzLpRY7xn9+/MGpcKKfbAplXeEDu4CmE/RMA3ZSmvv34wNYJPMLo/x1TnMcdH5CY5PM/CTpQ76sWLq54SkRehLdGjwL9m8YuvwCO+87cGn9p8bL0mGmBlc7o9qnvMDwARfxxMNYJq+Wn1+I72h6iGnpwiaFDD2y2ybBrYkGBpFuDQ5FT76aWmdAb/jF7O4ASqFktkeHDd8CzYANrUeBpHhSF6crmBkkcyUCM8zrZgJvw+LrJqjr9eDjd2AttVofRHleG5q8IH4EN666HA7F6RuIqfn4+BlPyg9+MyHv27EPEJVlxcYMEQxKuFSVXh8ETtlrvnNgBt07Q6cRBl6XKvzUOhpH05MuhGtneOuRaYEPcpz4mrCQlkNVx+ZXl8zfFQ0OxWXZ0+6fS307t9PcrigrF8wBO9g5Xx8mTMp4uKoZKPyDUpeVzvS2CQom6xUckPfUbk7CpJ44U0xfBL9YWSD1/lH/uAPB1wgxjSXn/84/SnMNZAZie2vjSBt3hKhK1I7in26V2jK62+Arfgg/Xi1xgtiYGVawxo/H1W/RAIEZorHMDGc72x0X0TmH0hDVEeCPTh0UjyBq8Nw/3AWnKa6W5lMB9fyyD/zAdeQXLBs0w4brpd2v+ycmmMTCMKiZQ5uShjQiPKj3LusU1sp1v7asn5ouzgA+JH38Afkrr5e8mS86li1fqDtHHYcDToYjD7nHnHVOzueT4QdgzTiuDQ8F97id3npsP4SOUC7w+eB4DVxd99Oil/9xUPpHfiLwwtpdpDqo6I+1ogCf2/Stx/YDAqrLDUh4RmJvB7olrPev5Rqwvv2IC42hR7vxV3HYfPmeGRx/kj2u1mbZyT/NSHxH1dkHMx1it9+PD2JsYYYoGjATKQAn3t+zgOMPgsdpbTg7+SnC25v82t3eVWF8c2wsoOdqBhff4T3kXZF63xvcZyk/Pz+whjiCZMyJ62ZJFs8X2wb2uPgE858n29nxIweF4x7bIZjVwkN8wfLv5HllPxRmOCFTXHgcAAuylH4qKafehDqDymy1TnwmQGlxppA7jpXswkFqtXKDnL3D/X39wZUbFuT2A4Hj20/t+vJdWp6PXWUgwf8="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 268,
      height = 51,
      id = 1,
      name = "Front",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zstd",
      data = "KLUv/WCQ1AUeAMJLDAjgAf+/KYfoA/F/////v5SljLKMuCy/5SpXXllZWWWVVV4qT+UuZSmlrJRSKnD8x1eCGahC7QlSC1iBUUVmARLAEAQcgggjABgMIABAgACACAKOoIEIOgAkYBhT1DlZDjiUiMGjJVC419IHD5Yg4naVN31Q0+YS37hRoRi/0+4CvA0fIxLkZwk1alDFzVkwRGUGjos2xCxBp3yUcLTqbko8MGI1iYd0Smj4fBCMH/Z614B4SuTtXwLAPP+YsQxcnmLNZwQl7HCX51jjCXXbMG5iH9sfqQKPPDT/Pr4/OIcA/G/1Q1HgoSKUUWVar+EMAvx4hrWEAO+VnPRYxsa/pJ0r5u+QD+mgmeB6WwpD5HDjPOKWgISfOd46WeiyEjoc1uC/I4GOlMDBCJr6H3WxRsADlIQ580MDO0FiYKX/7GJmQ/iA98uzWY4btv/HT3seEDWaoQ3oAAkn2sBSzB/HR8d0Br5xk49Y+eVG0HS2PLARIM2mGo8i0xSj+OONHT4YPZ+Peo6Tv5qtIhfYlcxXB9PkS5Qpo53IYAp3law46kD76BvLGJuGJ6xncCdRyzNHXcvWhRAznk4ppOYqWXHURtpf7iC/YY0x6Z0vB9yR2XrGTIDSjJNnoSP3XklaZ2EK/r9wKCoyafzcGkVV/k2Glzbe2052J9mBce9FHvw8k73rQgYt76vJJ1Vb10lYc+FXHcIrfzUHIa5OGeCYMqcuKc6iuBQOqr8NFWnezimfFLIoLwXH6n93ilGYGqPC7A14uHMqTZEQE8u5CFj3/C6wo760+cYmzeXb8dh7ygrgtQLarG74BUZYt+kQv0uoXyxYFF6y0cEG8r09eXbdeI6XwTw+wRHrXVQBCLjHzvyUTeMxDewX54qD8cUExzpdxOjAXkYcOR5GwCqXAIdrPIzYU+9EXxW8/NmU1lUkTVNy19tk1UPtT6KXE1JIROP8P9EwAK139J2k5ACYzuVj8KqiucmbHihaJ6HfYaeYgR79shch28BCT2OOdNDBTqnBvklPdQhaA8ifTsSPTBFqsMBkJhmboY19tMOwzXFcO8FHzJx9FyQyqRnS2a6CeYiWEV22GddJSO5Wjz435dqTDn5U7HSVV4ZKHmL+kU4wvnFXZ4YG5aOkDY0uZM1DNUgyDYehGdrIR1uearN2VS4c3QXAj+U0cvmU1jpiuXUs+2HBcvQjXEgbCGKAFl5gbXqn7zasmRliTdF+Op/p/9bDC+qrD/rl2lROzJRGSnE5SFG1iM75z16KacmJ8Ep+bIn+AQ=="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "MovingPlatform",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 170,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7328,
          y = 896,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 7328,
            ["ey"] = 896,
            ["isDeadly"] = false,
            ["speed"] = 200,
            ["sx"] = 6400,
            ["sy"] = 896
          }
        },
        {
          id = 177,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6400,
          y = 832,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 7328,
            ["ey"] = 832,
            ["isDeadly"] = true,
            ["speed"] = 200,
            ["sx"] = 6400,
            ["sy"] = 832
          }
        },
        {
          id = 187,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7904,
          y = 1376,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 7872,
            ["ey"] = 1376,
            ["isDeadly"] = false,
            ["speed"] = 150,
            ["sx"] = 7872,
            ["sy"] = 896
          }
        },
        {
          id = 188,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6912,
          y = 1344,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 6912,
            ["ey"] = 1504,
            ["isDeadly"] = false,
            ["speed"] = 100,
            ["sx"] = 6912,
            ["sy"] = 1344
          }
        },
        {
          id = 189,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6624,
          y = 1440,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 6624,
            ["ey"] = 1504,
            ["isDeadly"] = false,
            ["speed"] = 100,
            ["sx"] = 6624,
            ["sy"] = 1344
          }
        },
        {
          id = 190,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6336,
          y = 1504,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 6336,
            ["ey"] = 1504,
            ["isDeadly"] = false,
            ["speed"] = 100,
            ["sx"] = 6336,
            ["sy"] = 1344
          }
        },
        {
          id = 191,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6528,
          y = 1184,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 6528,
            ["ey"] = 1504,
            ["isDeadly"] = true,
            ["speed"] = 150,
            ["sx"] = 6528,
            ["sy"] = 1184
          }
        },
        {
          id = 192,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6816,
          y = 1504,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 6816,
            ["ey"] = 1504,
            ["isDeadly"] = true,
            ["speed"] = 150,
            ["sx"] = 6816,
            ["sy"] = 1184
          }
        },
        {
          id = 371,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5664,
          y = 384,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 6624,
            ["ey"] = 384,
            ["isDeadly"] = false,
            ["speed"] = 100,
            ["sx"] = 5216,
            ["sy"] = 384
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "Trampolines",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 163,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3776,
          y = 960,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 201,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6016,
          y = 1440,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 202,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6016,
          y = 1248,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = -1,
            ["directionY"] = 0
          }
        },
        {
          id = 219,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5344,
          y = 1248,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        },
        {
          id = 220,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5120,
          y = 1248,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        },
        {
          id = 221,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5344,
          y = 1344,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = -1,
            ["directionY"] = 0
          }
        },
        {
          id = 222,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5120,
          y = 1344,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = -1,
            ["directionY"] = 0
          }
        },
        {
          id = 223,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4992,
          y = 1216,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = -1,
            ["directionY"] = 0
          }
        },
        {
          id = 224,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4992,
          y = 1344,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 225,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5248,
          y = 1344,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 226,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5248,
          y = 1248,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = -1,
            ["directionY"] = 0
          }
        },
        {
          id = 227,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4480,
          y = 1280,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        },
        {
          id = 228,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4480,
          y = 1408,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 229,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4608,
          y = 1472,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 230,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4736,
          y = 1376,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 231,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4864,
          y = 1504,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 232,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4992,
          y = 1440,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 233,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5120,
          y = 1536,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 234,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5248,
          y = 1440,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 235,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5312,
          y = 1504,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 236,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5376,
          y = 1440,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 237,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5504,
          y = 1504,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 238,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5568,
          y = 1408,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 239,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5632,
          y = 1408,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 240,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5568,
          y = 1504,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 241,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5376,
          y = 1504,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 242,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5248,
          y = 1536,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 243,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4992,
          y = 1504,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 244,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4736,
          y = 1472,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 245,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4864,
          y = 1376,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        },
        {
          id = 246,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5120,
          y = 1440,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        },
        {
          id = 247,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5312,
          y = 1440,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        },
        {
          id = 248,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5504,
          y = 1440,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        },
        {
          id = 284,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4608,
          y = 1408,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        },
        {
          id = 363,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7232,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 366,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7072,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "Collectables",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 50,
          name = "strawberry",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 1056,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "dash",
          type = "",
          shape = "rectangle",
          x = 4608,
          y = 1280,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "Walls",
      visible = false,
      opacity = 0.79,
      offsetx = 0,
      offsety = 0,
      tintcolor = { 255, 0, 0 },
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 512,
          width = 2720,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2368,
          y = 1024,
          width = 1120,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 1024,
          width = 1312,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1920,
          y = 960,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 992,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2080,
          y = 992,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 608,
          width = 1120,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 576,
          width = 2720,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1760,
          y = 608,
          width = 896,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2656,
          y = 608,
          width = 64,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3200,
          y = 896,
          width = 160,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2368,
          y = 960,
          width = 512,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2528,
          y = 928,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2592,
          y = 928,
          width = 288,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2688,
          y = 896,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2880,
          y = 992,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3136,
          y = 864,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3360,
          y = 928,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3488,
          y = 1056,
          width = 832,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3616,
          y = 1024,
          width = 704,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3776,
          y = 992,
          width = 288,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3808,
          y = 928,
          width = 224,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2720,
          y = 544,
          width = 4384,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2720,
          y = 576,
          width = 320,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2720,
          y = 640,
          width = 256,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2784,
          y = 672,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3040,
          y = 576,
          width = 736,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3680,
          y = 608,
          width = 96,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3648,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3392,
          y = 608,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3104,
          y = 608,
          width = 128,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3840,
          y = 576,
          width = 4288,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3872,
          y = 608,
          width = 3136,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3872,
          y = 640,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 608,
          width = 640,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 640,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 672,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 704,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 640,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 640,
          width = 320,
          height = 448,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1088,
          width = 1056,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 736,
          width = 256,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 768,
          width = 128,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 864,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 960,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 864,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 736,
          width = 384,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 1024,
          width = 224,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 1056,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 1056,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4000,
          y = 640,
          width = 704,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4160,
          y = 672,
          width = 544,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4064,
          y = 672,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4256,
          y = 736,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4416,
          y = 736,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4896,
          y = 640,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5024,
          y = 640,
          width = 736,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5792,
          y = 640,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5760,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5888,
          y = 640,
          width = 672,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5920,
          y = 672,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6080,
          y = 672,
          width = 352,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6368,
          y = 704,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6112,
          y = 704,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6208,
          y = 704,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5344,
          y = 704,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5088,
          y = 704,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4064,
          y = 992,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4320,
          y = 1088,
          width = 3552,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6048,
          y = 992,
          width = 352,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6112,
          y = 864,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6048,
          y = 896,
          width = 352,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5856,
          y = 896,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5632,
          y = 896,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5408,
          y = 896,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4928,
          y = 1056,
          width = 1120,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4928,
          y = 1024,
          width = 416,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5184,
          y = 928,
          width = 160,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5088,
          y = 992,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5152,
          y = 960,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5216,
          y = 864,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5248,
          y = 896,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4480,
          y = 1024,
          width = 288,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4544,
          y = 992,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4384,
          y = 1024,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 165,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3808,
          y = 864,
          width = 128,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3808,
          y = 832,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3808,
          y = 800,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6400,
          y = 1056,
          width = 1472,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 172,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7456,
          y = 896,
          width = 416,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7968,
          y = 672,
          width = 96,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7168,
          y = 608,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 180,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6816,
          y = 640,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8032,
          y = 896,
          width = 544,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8224,
          y = 672,
          width = 352,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 194,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7392,
          y = 1152,
          width = 480,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 195,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8032,
          y = 1152,
          width = 544,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 196,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7360,
          y = 1440,
          width = 1216,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 197,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7200,
          y = 1472,
          width = 160,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 198,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7072,
          y = 1504,
          width = 128,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 199,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7584,
          y = 1408,
          width = 448,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 203,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5760,
          y = 1152,
          width = 352,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 204,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6048,
          y = 1248,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 206,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5728,
          y = 1312,
          width = 288,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 207,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5600,
          y = 1440,
          width = 416,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 209,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5600,
          y = 1472,
          width = 640,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 210,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5280,
          y = 1536,
          width = 960,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 249,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4608,
          y = 1152,
          width = 1152,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 250,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5696,
          y = 1216,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 251,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5664,
          y = 1280,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 252,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5664,
          y = 1312,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 255,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5664,
          y = 1408,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 256,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4416,
          y = 1568,
          width = 864,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 257,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4416,
          y = 1504,
          width = 448,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 258,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4864,
          y = 1536,
          width = 256,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 259,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5024,
          y = 1472,
          width = 96,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 260,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4416,
          y = 1440,
          width = 192,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 261,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4416,
          y = 1152,
          width = 64,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 262,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4480,
          y = 1152,
          width = 128,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 263,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4480,
          y = 1248,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 264,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4608,
          y = 1216,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 265,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4512,
          y = 1312,
          width = 480,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 266,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4736,
          y = 1248,
          width = 256,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 267,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4704,
          y = 1280,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 268,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4512,
          y = 1376,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 269,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4640,
          y = 1376,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 270,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4768,
          y = 1408,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 271,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4896,
          y = 1376,
          width = 96,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 272,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5024,
          y = 1376,
          width = 544,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 273,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5152,
          y = 1280,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 274,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5024,
          y = 1216,
          width = 96,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 275,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5120,
          y = 1216,
          width = 384,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 276,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5280,
          y = 1248,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 277,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5376,
          y = 1280,
          width = 256,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 278,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5568,
          y = 1376,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5536,
          y = 1440,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 280,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5408,
          y = 1472,
          width = 96,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 281,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5344,
          y = 1440,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 282,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5280,
          y = 1472,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 283,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5152,
          y = 1440,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 285,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4992,
          y = 1376,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 293,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8288,
          y = 640,
          width = 288,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 294,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7488,
          y = 512,
          width = 448,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 296,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8000,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 297,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7456,
          y = 608,
          width = 672,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 298,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8064,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 299,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7616,
          y = 672,
          width = 288,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 300,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7584,
          y = 672,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 301,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7808,
          y = 704,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 302,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7872,
          y = 704,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 303,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8192,
          y = 704,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 304,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8352,
          y = 608,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 305,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8512,
          y = 0,
          width = 64,
          height = 640,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 306,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8480,
          y = 416,
          width = 32,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 307,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8416,
          y = 416,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 308,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8448,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 309,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8480,
          y = 0,
          width = 32,
          height = 352,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 310,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8448,
          y = 0,
          width = 32,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 312,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7296,
          y = 0,
          width = 1152,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 313,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7328,
          y = 96,
          width = 1120,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 315,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7456,
          y = 128,
          width = 544,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 318,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7488,
          y = 160,
          width = 544,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 320,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7616,
          y = 192,
          width = 416,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 321,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7680,
          y = 224,
          width = 352,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 322,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7616,
          y = 320,
          width = 256,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 323,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7872,
          y = 320,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 324,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8096,
          y = 128,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 325,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8416,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 326,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8192,
          y = 256,
          width = 96,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 327,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8288,
          y = 256,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 328,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8320,
          y = 288,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 329,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8352,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 331,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8160,
          y = 288,
          width = 32,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 332,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8128,
          y = 320,
          width = 32,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 333,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8096,
          y = 512,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 334,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8096,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 335,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8192,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 337,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2720,
          y = 512,
          width = 4384,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 338,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7616,
          y = 384,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 340,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7008,
          y = 416,
          width = 96,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 342,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7488,
          y = 544,
          width = 480,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 343,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7200,
          y = 512,
          width = 192,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 345,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6816,
          y = 352,
          width = 96,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 346,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6912,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 348,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6848,
          y = 320,
          width = 704,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 349,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7488,
          y = 352,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 350,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6880,
          y = 288,
          width = 544,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 352,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6976,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 353,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6912,
          y = 352,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 354,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6912,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 355,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7200,
          y = 416,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 356,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7488,
          y = 416,
          width = 192,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 357,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7648,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 359,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7648,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 364,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6432,
          y = 0,
          width = 864,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 365,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6528,
          y = 32,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 372,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5088,
          y = 256,
          width = 128,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "Hazards",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 112,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4320,
          y = 1056,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4416,
          y = 1056,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4768,
          y = 1056,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5344,
          y = 1024,
          width = 704,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 175,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6400,
          y = 1024,
          width = 1056,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 200,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6240,
          y = 1600,
          width = 832,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 341,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7392,
          y = 544,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 344,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7104,
          y = 544,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 361,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7104,
          y = 448,
          width = 384,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 362,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7104,
          y = 352,
          width = 384,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 367,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7136,
          y = 128,
          width = 64,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 368,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6976,
          y = 128,
          width = 64,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 373,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5216,
          y = 480,
          width = 1600,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 374,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5536,
          y = 288,
          width = 64,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 375,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5888,
          y = 288,
          width = 64,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 376,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6304,
          y = 288,
          width = 64,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "EventTriggers",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 73,
          name = "trigger_first_jump",
          type = "",
          shape = "rectangle",
          x = 1312,
          y = 736,
          width = 128,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "trigger_long_jump",
          type = "",
          shape = "rectangle",
          x = 2496,
          y = 672,
          width = 224,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "trigger_long_jump_end",
          type = "",
          shape = "rectangle",
          x = 3264,
          y = 608,
          width = 64,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "trigger_first_trampoline",
          type = "",
          shape = "rectangle",
          x = 3392,
          y = 640,
          width = 64,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "trigger_first_hazard",
          type = "",
          shape = "rectangle",
          x = 4032,
          y = 672,
          width = 64,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "trigger_second_hazard",
          type = "",
          shape = "rectangle",
          x = 5088,
          y = 736,
          width = 64,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "PlayerObjects",
      visible = false,
      opacity = 0.75,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 176,
          name = "player_spawn",
          type = "",
          shape = "rectangle",
          x = 6880,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 287,
          name = "player_checkpoint",
          type = "",
          shape = "rectangle",
          x = 4160,
          y = 960,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 289,
          name = "player_checkpoint",
          type = "",
          shape = "rectangle",
          x = 5280,
          y = 864,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 290,
          name = "player_checkpoint",
          type = "",
          shape = "rectangle",
          x = 6272,
          y = 864,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 291,
          name = "player_checkpoint",
          type = "",
          shape = "rectangle",
          x = 7744,
          y = 864,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 292,
          name = "player_checkpoint",
          type = "",
          shape = "rectangle",
          x = 6080,
          y = 1440,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
