return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "2020.04.10",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 300,
  height = 35,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 11,
  nextobjectid = 287,
  properties = {
    ["darkness"] = 0.10000000000000001
  },
  tilesets = {
    {
      name = "MyTileset",
      firstgid = 1,
      filename = "MyTileset.tsx",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      terrains = {},
      tilecount = 7,
      tiles = {
        {
          id = 1,
          image = "wall old.png",
          width = 32,
          height = 32
        },
        {
          id = 3,
          image = "prototype_wall.png",
          width = 32,
          height = 32
        },
        {
          id = 4,
          image = "wall black.png",
          width = 32,
          height = 32
        },
        {
          id = 9,
          image = "blueDark1.png",
          width = 32,
          height = 32,
          probability = 0.2
        },
        {
          id = 10,
          image = "blueDark2.png",
          width = 32,
          height = 32
        },
        {
          id = 11,
          image = "blueDark3.png",
          width = 32,
          height = 32
        },
        {
          id = 12,
          image = "Hot_tile.png",
          width = 32,
          height = 32
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 300,
      height = 35,
      id = 4,
      name = "Background",
      visible = true,
      opacity = 0.8,
      offsetx = 18,
      offsety = 9,
      properties = {},
      encoding = "base64",
      compression = "zstd",
      data = "KLUv/WAQo1UTADIJDQvAAQDDEoZhyN14fdNtrsk1N9xKmiVNZU3apGdJg6zSbJqdQMRU2YSZhmXYhKdMNEQ0IgqBSahh+gIBBhoM1AwJABIAAQhEEXQUQYURABgGABhHkGAEAUaIBAgoB5kUTPEa3QfnRc75OVdx+Cqs/cP/vT+czNw+x8LpTZtu3FE+0ghHP+fHKvjx9p33FZPGt+xFjf0tjNgw+5owpqoR8EnYQOQfMGfP0u3ttwfRCAFy4/9fmxROsjuYspWhUj4mEOR7l8HMWDr0Cg2D6knP9ZG+ES+km/v5XuBOHfjJvgD+Z059Eww4rVcHsAit1pX1DrValxw4oLPcDGJjIw2NQkUn0T10tPGnQ2a5J/998EnHfT0cyMmcVY8XoH1lqpeu0PsJDrUvX6uGmkUgaAg7GungiMhhd+59BPDMNog1cFAUOUTlbqFytL4DZy6rnTrUA12lzKoF0lIkZXB8jBfNQukDbgYOghGNbDgedIoAOVVqiw42GwvnPHh2Paqvpzy4TJxZs4FZGKdB4gduIaxsZEhM9k0qO57D5XBrOUISB4+pgY5ncDHcW4yQyMGxpMJ2ysP8/hh/hsdGoIscN8/PUcc4gYwpjz0YgRJzd8Vao2PhwCtuvEb2nDW6nB8P0MjcFqZGVMKAQXxlL/etaWSFO6CR86NocJE25jolpIOxt2Vf7kV/fPKEu5HitzY2P8e/XkqP3KLC+nEy7tuIVZNyHB9yydNITS8jNT9n/zC09EeHzBdXfaN+ngLSLL+05sdTdH+/fpaw2/+LEPcwWf3B+1WZtzYSiZnz88vx2sZhyus7JTQq9dr9Bw=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 300,
      height = 35,
      id = 1,
      name = "Front",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zstd",
      data = "KLUv/WAQo/UXADJGBwjgAf+/KYfoA/F///8/mVFGXP6ue9vMqS4lKaUGgbqoMXsB8QUkDGn0EsAQBByAACIBAoADCACMIKAIAoyggQACDMAIKIYhqCx7B0GEakgEvDydhl4UDXx/Ohq9K0J6TYMOSaejl4U7tulb3Rhpio2BPYdJ1yPflUG+A8OgTKkjQgsD7brztISSni7nJqNsqQbywne7GliCv/imVgc4JZmg6Pwxv7W+Pz2UcQz4j8d1HHC+Kt+1vn9x0M/nyq8yEtvY93yZj1PfQ6MIgblq6uoYRxBoJx8hZ2Oo2KiSN0QP1M/1BA/nb+eflyACC9XYRo98hH6x3YH8vPfvhQWw0m8p/8PKCnj88kdOOHwj+IxRJwa9DHfaOLsx7kShl61uwg6f0I6ODAlG4dT1eygFKPgO6RSOn2AAltxdSROhQAm8QcZGuFfrJ/XM7S38z+IXkN/cy4pHysIEXOoBDUjmBMWwGLdt+y4eHWIScUpfCcwthJcY6QvXcE2ES8CLa4vYKZg15YS5uvoORED6dR/TjyW/6paWpD+vNbLLeRiMwwzLsxKu0E5BtsJdeIU44IHwG27kuzbVJnKdw0UyC8yRbgkMwBqRaXUWYa10Opua66+IA1YG62JnfKPGAKevvm+w+vdIWiCEq154BpiQ1+Thd5T+JW2dxYH0G4NDu0irzfO62XrSPqkFoj5I+KUNxHbajtfB2b3JeYh5KOlrutW0f94pXUDoTKZftYUnMTWH8r7F5IqY8aXstkNNHYJxpRs1fbBCrjhqIhk7zVL74BSB1lNyOjsbT9ZmOU6gbR3u3+HtFxrRsrZXtct8d4laTPa5v0Q9dqHsbfIrBQfHJbI/uFOyYpefeJjHFwle6X5RCMzh3jTVi/jD89dHCeDUNnx5YEyfKBVo9g4KB3Kg4Yh9JOSGg2fgb4FbbH+9AgzXx4P0PiOCvt+og/4hhY7QA1ipl+Sv5oFJvEJEsxyvfkqZhMC+5S+NQyzpOhLKVDi6Yn9FGamNRjkBh4hGPH8="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "MovingPlatform",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 170,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6624,
          y = 384,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 7296,
            ["ey"] = 448,
            ["isDeadly"] = false,
            ["speed"] = 200,
            ["sx"] = 6400,
            ["sy"] = 448
          }
        },
        {
          id = 177,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6816,
          y = 448,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 7296,
            ["ey"] = 416,
            ["isDeadly"] = true,
            ["speed"] = 180,
            ["sx"] = 6400,
            ["sy"] = 416
          }
        },
        {
          id = 187,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7872,
          y = 544,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 7872,
            ["ey"] = 864,
            ["isDeadly"] = false,
            ["speed"] = 150,
            ["sx"] = 7872,
            ["sy"] = 384
          }
        },
        {
          id = 188,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6912,
          y = 832,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 6912,
            ["ey"] = 992,
            ["isDeadly"] = false,
            ["speed"] = 100,
            ["sx"] = 6912,
            ["sy"] = 832
          }
        },
        {
          id = 189,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6624,
          y = 928,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 6624,
            ["ey"] = 992,
            ["isDeadly"] = false,
            ["speed"] = 100,
            ["sx"] = 6624,
            ["sy"] = 832
          }
        },
        {
          id = 190,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6336,
          y = 992,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 6336,
            ["ey"] = 992,
            ["isDeadly"] = false,
            ["speed"] = 100,
            ["sx"] = 6336,
            ["sy"] = 832
          }
        },
        {
          id = 191,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6528,
          y = 736,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 6528,
            ["ey"] = 1024,
            ["isDeadly"] = true,
            ["speed"] = 150,
            ["sx"] = 6528,
            ["sy"] = 672
          }
        },
        {
          id = 192,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6816,
          y = 1024,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {
            ["ex"] = 6816,
            ["ey"] = 1024,
            ["isDeadly"] = true,
            ["speed"] = 150,
            ["sx"] = 6816,
            ["sy"] = 672
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "Trampolines",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 163,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3776,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 201,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6016,
          y = 928,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 202,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6016,
          y = 736,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = -1,
            ["directionY"] = 0
          }
        },
        {
          id = 219,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5344,
          y = 736,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        },
        {
          id = 220,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5120,
          y = 736,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        },
        {
          id = 221,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5344,
          y = 832,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = -1,
            ["directionY"] = 0
          }
        },
        {
          id = 222,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5120,
          y = 832,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = -1,
            ["directionY"] = 0
          }
        },
        {
          id = 223,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4992,
          y = 704,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = -1,
            ["directionY"] = 0
          }
        },
        {
          id = 224,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4992,
          y = 832,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 225,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5248,
          y = 832,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 226,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5248,
          y = 736,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = -1,
            ["directionY"] = 0
          }
        },
        {
          id = 227,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4480,
          y = 768,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        },
        {
          id = 228,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4480,
          y = 896,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 229,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4608,
          y = 960,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 230,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4736,
          y = 864,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 231,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4864,
          y = 992,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 232,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4992,
          y = 928,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 233,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5120,
          y = 1024,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 234,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5248,
          y = 928,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 235,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5312,
          y = 992,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 236,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5376,
          y = 928,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 237,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5504,
          y = 992,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 238,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5568,
          y = 896,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 1,
            ["directionY"] = 0
          }
        },
        {
          id = 239,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5632,
          y = 896,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 240,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5568,
          y = 992,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 241,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5376,
          y = 992,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 242,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5248,
          y = 1024,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 243,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4992,
          y = 992,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 244,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4736,
          y = 960,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = -1
          }
        },
        {
          id = 245,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4864,
          y = 864,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        },
        {
          id = 246,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5120,
          y = 928,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        },
        {
          id = 247,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5312,
          y = 928,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        },
        {
          id = 248,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5504,
          y = 928,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        },
        {
          id = 284,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4608,
          y = 896,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["directionX"] = 0,
            ["directionY"] = 1
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "Collectables",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 50,
          name = "strawberry",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "powered_jump",
          type = "",
          shape = "rectangle",
          x = 4608,
          y = 768,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "Walls",
      visible = false,
      opacity = 0.79,
      offsetx = 0,
      offsety = 0,
      tintcolor = { 255, 0, 0 },
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 2720,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2368,
          y = 512,
          width = 1120,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 512,
          width = 1312,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1920,
          y = 448,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2080,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 96,
          width = 1120,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 64,
          width = 2720,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1760,
          y = 96,
          width = 896,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2656,
          y = 96,
          width = 64,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3200,
          y = 384,
          width = 160,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2368,
          y = 448,
          width = 512,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2528,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2592,
          y = 416,
          width = 288,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2688,
          y = 384,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2880,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3136,
          y = 352,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3360,
          y = 416,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3488,
          y = 544,
          width = 832,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3616,
          y = 512,
          width = 704,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3776,
          y = 480,
          width = 288,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3808,
          y = 416,
          width = 224,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2720,
          y = 0,
          width = 4928,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2720,
          y = 64,
          width = 320,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2720,
          y = 128,
          width = 256,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2784,
          y = 160,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3040,
          y = 64,
          width = 736,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3680,
          y = 96,
          width = 96,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3648,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3392,
          y = 96,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3104,
          y = 96,
          width = 128,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3840,
          y = 64,
          width = 3744,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3872,
          y = 96,
          width = 3136,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3872,
          y = 128,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 96,
          width = 640,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 128,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 160,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 128,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 128,
          width = 320,
          height = 448,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 576,
          width = 1056,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 224,
          width = 256,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 256,
          width = 128,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 352,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 224,
          width = 384,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 512,
          width = 224,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 544,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4000,
          y = 128,
          width = 704,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4160,
          y = 160,
          width = 544,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4064,
          y = 160,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4256,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4416,
          y = 224,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4896,
          y = 128,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5024,
          y = 128,
          width = 736,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5792,
          y = 128,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5760,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5888,
          y = 128,
          width = 672,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5920,
          y = 160,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6080,
          y = 160,
          width = 352,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6368,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6112,
          y = 192,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6208,
          y = 192,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5344,
          y = 192,
          width = 192,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5088,
          y = 192,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4064,
          y = 480,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4320,
          y = 576,
          width = 3552,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6048,
          y = 480,
          width = 352,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6112,
          y = 352,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6048,
          y = 384,
          width = 352,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5856,
          y = 384,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5632,
          y = 384,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5408,
          y = 384,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4928,
          y = 544,
          width = 1120,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4928,
          y = 512,
          width = 416,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5184,
          y = 416,
          width = 160,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5088,
          y = 480,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5152,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5216,
          y = 352,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5248,
          y = 384,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4480,
          y = 512,
          width = 288,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4544,
          y = 480,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4384,
          y = 512,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 165,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3808,
          y = 352,
          width = 128,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3808,
          y = 320,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3808,
          y = 288,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6400,
          y = 544,
          width = 1472,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 172,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7456,
          y = 384,
          width = 416,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7648,
          y = 0,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7168,
          y = 96,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 180,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6816,
          y = 128,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7968,
          y = 384,
          width = 544,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8192,
          y = 256,
          width = 320,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 186,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8288,
          y = 224,
          width = 224,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 194,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7392,
          y = 640,
          width = 480,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 195,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7968,
          y = 640,
          width = 32,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 196,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7360,
          y = 928,
          width = 640,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 197,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7200,
          y = 960,
          width = 160,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 198,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7072,
          y = 992,
          width = 128,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 199,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7584,
          y = 896,
          width = 384,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 203,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5760,
          y = 640,
          width = 352,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 204,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6048,
          y = 736,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 206,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5728,
          y = 800,
          width = 288,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 207,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5600,
          y = 928,
          width = 416,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 209,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5600,
          y = 960,
          width = 640,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 210,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5280,
          y = 1024,
          width = 960,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 249,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4608,
          y = 640,
          width = 1152,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 250,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5696,
          y = 704,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 251,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5664,
          y = 768,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 252,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5664,
          y = 800,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 255,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5664,
          y = 896,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 256,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4416,
          y = 1056,
          width = 864,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 257,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4416,
          y = 992,
          width = 448,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 258,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4864,
          y = 1024,
          width = 256,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 259,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5024,
          y = 960,
          width = 96,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 260,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4416,
          y = 928,
          width = 192,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 261,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4416,
          y = 640,
          width = 64,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 262,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4480,
          y = 640,
          width = 128,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 263,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4480,
          y = 736,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 264,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4608,
          y = 704,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 265,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4512,
          y = 800,
          width = 480,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 266,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4736,
          y = 736,
          width = 256,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 267,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4704,
          y = 768,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 268,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4512,
          y = 864,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 269,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4640,
          y = 864,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 270,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4768,
          y = 896,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 271,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4896,
          y = 864,
          width = 96,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 272,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5024,
          y = 864,
          width = 544,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 273,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5152,
          y = 768,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 274,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5024,
          y = 704,
          width = 96,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 275,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5120,
          y = 704,
          width = 384,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 276,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5280,
          y = 736,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 277,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5376,
          y = 768,
          width = 256,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 278,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5568,
          y = 864,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5536,
          y = 928,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 280,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5408,
          y = 960,
          width = 96,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 281,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5344,
          y = 928,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 282,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5280,
          y = 960,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 283,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5152,
          y = 928,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 285,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4992,
          y = 864,
          width = 32,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "Hazards",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 112,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4320,
          y = 544,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4416,
          y = 544,
          width = 64,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4768,
          y = 544,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5344,
          y = 512,
          width = 704,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 175,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6400,
          y = 512,
          width = 1056,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 200,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6240,
          y = 1088,
          width = 832,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "EventTriggers",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 73,
          name = "trigger_first_jump",
          type = "",
          shape = "rectangle",
          x = 1312,
          y = 224,
          width = 128,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "trigger_long_jump",
          type = "",
          shape = "rectangle",
          x = 2496,
          y = 160,
          width = 224,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "trigger_long_jump_end",
          type = "",
          shape = "rectangle",
          x = 3264,
          y = 96,
          width = 64,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "trigger_first_trampoline",
          type = "",
          shape = "rectangle",
          x = 3392,
          y = 128,
          width = 64,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "trigger_first_hazard",
          type = "",
          shape = "rectangle",
          x = 4032,
          y = 160,
          width = 64,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "trigger_second_hazard",
          type = "",
          shape = "rectangle",
          x = 5088,
          y = 224,
          width = 64,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "PlayerObjects",
      visible = false,
      opacity = 0.75,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 176,
          name = "player_spawn",
          type = "",
          shape = "rectangle",
          x = 1696,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
